server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: receipt
          uri: http://localhost:8082
          predicates:
            - Path=/complainments/**, 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/fees/**, 
        - id: user
          uri: http://localhost:8084
          predicates:
            - Path=/users/**, 
        - id: search
          uri: http://localhost:8085
          predicates:
            - Path=/searchEngines/**, 
        - id: 통계
          uri: http://localhost:8086
          predicates:
            - Path=/starSchemes/**, 
        - id: 연계
          uri: http://localhost:8087
          predicates:
            - Path=/연계/**, 
        - id: 주문
          uri: http://localhost:8088
          predicates:
            - Path=/주문/**, 
        - id: 게시판
          uri: http://localhost:8089
          predicates:
            - Path=/게시물/**, /댓글/**, 
        - id: 게시판2
          uri: http://localhost:8090
          predicates:
            - Path=/게시물/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: receipt
          uri: http://receipt:8080
          predicates:
            - Path=/complainments/**, 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/fees/**, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: search
          uri: http://search:8080
          predicates:
            - Path=/searchEngines/**, 
        - id: 통계
          uri: http://통계:8080
          predicates:
            - Path=/starSchemes/**, 
        - id: 연계
          uri: http://연계:8080
          predicates:
            - Path=/연계/**, 
        - id: 주문
          uri: http://주문:8080
          predicates:
            - Path=/주문/**, 
        - id: 게시판
          uri: http://게시판:8080
          predicates:
            - Path=/게시물/**, /댓글/**, 
        - id: 게시판2
          uri: http://게시판2:8080
          predicates:
            - Path=/게시물/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
