apiVersion: apps/v1
kind: Deployment
metadata:
  name: 게시판2
  labels:
    app: 게시판2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 게시판2
  template:
    metadata:
      labels:
        app: 게시판2
    spec:
      containers:
        - name: 게시판2
          image: "username/게시판2:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
